### ISSUE TITLE
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

### ISSUE THREAD

**Issue by liuchunming2** [KatherLab/marugoto#16]
Hello, when I was performing feature extraction,When I execute this command   
       python -m marugoto.extract.xiyue_wang \
        --checkpoint-path ~/Downloads/best_ckpt.pth \
        --outdir ~/TCGA_features/TCGA-CRC-DX-features/xiyue-wang \
        /mnt/TCGA_BLOCKS/TCGA-CRC-DX-BLOCKS/*
I made an error，TypeError: Object dtype dtype('O') has no native HDF5 equivalent
and I would like to ask if you could provide the command/mnt/TCGA-Blocks/TCGA-CRC-DX-BLOCKS/*，How to change to my path, because after changing my path, he cannot detect the images in the folder in my folder

Looking forward to your reply！

**Comment by Avic3nna** [comment]
Hi @liuchunming2 , please use our latest protocol paper which relieves a lot of these issues, paired with extensive documentation. Check it out here: https://github.com/KatherLab/STAMP
