### ISSUE TITLE
Regression Task sample csv

### ISSUE THREAD

**Issue by shubhaminnani** [KatherLab/marugoto#17]
Hi,
I am trying to implement the regression model for a task but I am not able to create a right csv, can you please share a sample csv in the repo, it will be really very helpful.

Thanks,
Shubham

**Comment by Avic3nna** [comment]
Hi Shubham, please check out the protocol paper we have released which provides information on how to design the tables and such. The protocol and corresponding preprint can be found here: https://github.com/KatherLab/STAMP
