### ISSUE TITLE
A question that puzzled me during the training stage

### ISSUE THREAD

**Issue by vergileZhang** [KatherLab/marugoto#18]
Hi！
When I tried to reproduce your paper on my own dataset, I encountered the following confusion in the "Train a single model on pre-extracted features" stage:
Since I think the labeling data for each patient is already given in the "clini-table" parameter, I wonder: what does the parameter "target-label" refer to? What format should it be in? What is the content stored inside?
I'm looking forward to your reply!

Thanks,
Vergile

**Comment by Avic3nna** [comment]
Please refer to the latest version of our pipeline which is accompanied by a protocol paper, which will answer your questions directly: https://github.com/KatherLab/STAMP

The content of the protocol is also applicable to the codebase of marugoto.

Thank you!
