### ISSUE TITLE
Feat: save model weights as hd5 to increase transparency of contents

### ISSUE THREAD

**Issue by YoniSchirris** [KatherLab/marugoto#2]
**Problem description**
Pickles may contain malicious code that is difficult to check (e.g. see solutions in https://huggingface.co/docs/hub/security-pickle). Wary users may not want to download pickled model weights.

**Current situation**
`torch.save` is used to save model weights, pickling weights

**Desired situation**
A more "open" way of saving model weights is used, or a ready-to-use safe-pickle script is provided.

**Suggested solution**
Use the suggestion in https://github.com/pytorch/pytorch/issues/52181 to save the model weights as an hd5. This requires a relatively heavy import and install, but is much more transparent and extremely easy to implement. I believe hd5 is already used for saving the features.

As taken from the given solution

---- 

We started using hdf5 for this after reading this thread. Made sense to us and wasn't too much work to set up. Something like

```
import h5py
path = 'item/'
model = torch.load(path_to_model.pt) 
with h5py.File(output_path.h5, 'w') as h5file:
    for key, item in model.items():
        h5file[path + key] = item
```
to secure the model

```
  from collections import OrderedDict
  file = h5py.File(output_path.h5)
  item = file["item"]
  keys = item.keys()
  dict_ = OrderedDict()
  for key in keys:
      dict_[key] = torch.tensor(item[key][()])
  torch.save(dict_, reconstructed_model.pt)
```

to get back the original

----

So likely implement some `marugoto.utils.models` with `save_h5_weights(model: torch.nn.Sequential, path: pathlib.Path) -> None` and `load_h5_weights(path: pathlib.Path) -> torch.nn.Sequential`, or something that's something similar to the torch `load` and `save` API.

**Comment by LocalToasty** [comment]
The way the pipeline currently rely on a lot of the metadata (concerning transforms, etc.) in the model, so it'd probably be more trouble than it's worth at the moment. I was thinking about transitioning the model to lightning and deprecating the fast.ai version at some point (because there's some other problems with fast.ai), so we could definitely incorporate that in the "new" version.
